---

version: "3"

services:
  houston:
    build:
      context: .
      dockerfile: Dockerfile-development
    network_mode: host
    environment:
      PORT: 4000
    volumes:
      - ./apps:/opt/houston/apps
      - ./config:/opt/houston/config
    command: do ecto.create, phx.server
    working_dir: /opt/houston
    depends_on:
      - postgres
      - mongo
      - browser

  postgres:
    image: timescale/timescaledb:latest-pg11
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  mongo:
    image: mongo:3.2
    network_mode: host
    volumes:
      - ./apps/houston_legacy/test/fixtures:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: houston_test

  browser:
    image: wernight/phantomjs
    network_mode: host
    command: phantomjs --webdriver=8910
